
import React from 'react';
import Link from 'next/link';
import { Button } from '@/components/ui/button'; 
import { Home } from 'lucide-react'; 

const TermsOfUsePage = () => {
  return (
    <div className="container mx-auto px-4 py-8 max-w-3xl">
      <h1 className="text-3xl font-bold mb-6 text-foreground">Terms of Use</h1>

      <p className="text-sm text-muted-foreground mb-6">Last updated: July 16, 2025</p>

      <section className="mb-6 space-y-2">
        <h2 className="text-2xl font-semibold mb-2 border-b pb-2">1. Acceptance of Terms</h2>
        <p>
          By accessing, downloading, or using the GutCheck application ("Service"), you agree to be bound by these Terms of Use ("Terms"). If you do not agree to these Terms, do not use the Service. These Terms constitute a legal agreement between you and the operators of GutCheck.
        </p>
      </section>

      <section className="mb-6 space-y-2">
        <h2 className="text-2xl font-semibold mb-2 border-b pb-2">2. Description of Service</h2>
        <p>
          GutCheck is a tool designed for informational and educational purposes only. It allows users to log food intake and personal symptoms, and it uses artificial intelligence to provide analysis, such as potential FODMAP content, nutritional estimates, and other health-related indicators.
        </p>
      </section>

      <section className="mb-6 space-y-2">
        <h2 className="text-2xl font-semibold mb-2 border-b pb-2">3. No Medical Advice - Disclaimer of Warranties</h2>
        <p className="font-bold text-destructive">
          THE SERVICE IS NOT A MEDICAL DEVICE AND DOES NOT PROVIDE MEDICAL ADVICE.
        </p>
        <p>
          GutCheck is not a substitute for professional medical advice, diagnosis, or treatment. The information and analysis provided by the Service are generated by an automated system and are for informational purposes only. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition. Never disregard professional medical advice or delay in seeking it because of something you have read or seen on the Service.
        </p>
        <p>
          The Service is provided "AS IS" and "AS AVAILABLE" without any warranties of any kind, express or implied, including but not limited to the implied warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not warrant that the Service will be accurate, reliable, complete, error-free, or uninterrupted.
        </p>
      </section>

      <section className="mb-6 space-y-2">
        <h2 className="text-2xl font-semibold mb-2 border-b pb-2">4. Limitation of Liability</h2>
        <p>
          TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE OPERATORS OF GUTCHECK, ITS AFFILIATES, OR THEIR RESPECTIVE EMPLOYEES, AGENTS, OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOOD-WILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:
        </p>
        <ul className="list-disc list-inside ml-4 space-y-1">
          <li>Your access to or use of or inability to access or use the Service.</li>
          <li>Any information, analysis, or content obtained from the Service, and any reliance you place on such information.</li>
          <li>Any personal injury or property damage resulting from your use of the Service.</li>
          <li>Any unauthorized access to or use of our servers and/or any and all personal information stored therein.</li>
        </ul>
        <p>
          Our total liability for any claim arising out of or relating to these Terms or the Service is limited to the greater of one dollar ($1.00) or any amount you paid us to use the Service.
        </p>
      </section>

      <section className="mb-6 space-y-2">
        <h2 className="text-2xl font-semibold mb-2 border-b pb-2">5. User Responsibilities</h2>
        <p>
          You are responsible for your use of the Service and for any consequences thereof. You are responsible for maintaining the confidentiality of your account login information and are fully responsible for all activities that occur under your account. You agree to use the Service in compliance with all applicable local, state, national, and international laws, rules, and regulations.
        </p>
      </section>

      <section className="mb-6 space-y-2">
        <h2 className="text-2xl font-semibold mb-2 border-b pb-2">6. Changes to Terms</h2>
        <p>
          We reserve the right to modify these Terms at any time. We will notify you of any changes by posting the new Terms of Use on this page. Your continued use of the Service after any such change constitutes your acceptance of the new Terms.
        </p>
      </section>

      <div className="mt-12 text-center">
        <Button asChild variant="outline">
          <Link href="/?openDashboard=true">
            <Home className="mr-2 h-4 w-4" /> Return to Dashboard
          </Link>
        </Button>
      </div>
    </div>
  );
};

export default TermsOfUsePage;
